### ISSUE TITLE
problem with XEM.XHY in wallet

### ISSUE THREAD

**Issue by twiettwiet** [hybrix-io/hybrixd#20]
I,m an ico-investor for IoC and my wallet is filled with XHY-tokens. (about 111.53 for each xhy-token.)
However, the balance of my XEM.XHY-token is zero. I think that is not correct.

More important: when I click the XEM.XHY-token I see a transaction crediting me 1 XEM.XHY-token
Notice the date of the transaction : year = 1973 ! 

Transaction ID: a4902f87f9a81a3f36b69a8e57b0faa31caf8ca54b575aa61ed85d23dacf4fe1
from ND65XD-QEDPT7-2JHJJY-AVKO2C-6EINQU-UHQMHV-SQEZ

The NEM-explorer shows this transaction on 2018-05-05 (Not 1973)
http://chain.nem.ninja/#/search/a4902f87f9a81a3f36b69a8e57b0faa31caf8ca54b575aa61ed85d23dacf4fe1

![xem_xhy](https://user-images.githubusercontent.com/48634200/81327943-5a269f80-909c-11ea-883f-7173d0ae8107.png)

**Comment by twiettwiet** [comment]
update: https://wallet2.internetofcoins.org/ shows the right date for the transaction, but has the sender as "from undefined".

https://explorer.nemtool.com/#/s_account?account=NDNSBP-DR5Y4D-QA64GN-5CFDKI-4HG74B-NJ2TSH-M2SA
Says the transaction is Mosaic transfer | internetofcoins:hybrid - 111.537142 and the 1 XEM.XHY is the fee. So my XEM.XHY balance should be 111.537142

This is confirmed at: http://chain.nem.ninja/#/search/NDNSBP-DR5Y4D-QA64GN-5CFDKI-4HG74B-NJ2TSH-M2SA  which says:           
Owned mosaics (most recent top 10)  internetofcoins.hybrid - 111.537142

**Comment by marcoalkema** [comment]
Thank you for notifying us of this bug. We will look into it and get back to you as soon as possible!

**Comment by agent725** [comment]
Tokens on XEM need periodic renewal. To avoid this recurring issue, XEM.XHY has been deprecated in favor of HY, which is the unified asset that replaces XHY assets. This issue will be closed.
