### ISSUE TITLE
Add XHY Ethereum token to MyEtherWallet

### ISSUE THREAD

**Issue by MickdeGraaf** [hybrix-io/hybrixd#3]
To allow myetherwallet users to easily send XHY tokens it might be worth the effort to add the token to this repo: https://github.com/MyEtherWallet/ethereum-lists/

**Comment by agent725** [comment]
@MickdeGraaf This is a good idea. Our marketing team is going to give us a timeline for this during the coming campaign. Then we will create a pull request for the MEW repo.

**Comment by agent725** [comment]
We have sent a pull request to MEW to add HY, the unified asset replacement for XHY. Now we must wait for their acceptance of our pull request into their next release.
